### ISSUE TITLE
Failed to run `npm run dev`

### ISSUE THREAD

**Issue by Phantom1003** [obsidianmd/obsidian-sample-plugin#55]
I'm using npm 8.5.1 and node 12.22.9, directly run the command will get following error:

```
$ npm run dev
> obsidian-sample-plugin@1.0.0 dev
> node esbuild.config.mjs

file:///mnt/f/obsidian/Phantom/.obsidian/plugins/obsidian-better-slides/esbuild.config.mjs:46
        await context.rebuild();
        ^^^^^

SyntaxError: Unexpected reserved word
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
    at async link (internal/modules/esm/module_job.js:42:21)
```

This is my first time developing a plugin, I wonder if there is something wrong with my environment.

**Comment by Phantom1003** [comment]
Fixed by updating node to v18.16.0
